"use client"
import './globals.css'
import type { Metadata } from 'next'
import { QueryClient, QueryClientProvider } from 'react-query'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const queryClient = new QueryClient()

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <QueryClientProvider client={queryClient}>
        {children}
      </QueryClientProvider>
        </body>
    </html>
  )
}
